package com.earnwage.app

// Compact, bundled UI dictionary: no third-party localization SDK or large assets.
// Occupational labels come from /v1/occupations?lang=...; untranslated source data stay original.
internal val languageNames = linkedMapOf(
    "pt" to "🇵🇹 Português", "en" to "🇬🇧 English", "es" to "🇪🇸 Español",
    "fr" to "🇫🇷 Français", "de" to "🇩🇪 Deutsch",
    "it" to "🇮🇹 Italiano", "nl" to "🇳🇱 Nederlands"
)
private val keys = "home|compare|jobs|settings|salary|tools|inflation|power|exchange|about|country|destination|occupation|search|language|currency|theme|system|light|dark|start|welcome|choose|open|unavailable|loading|remote|disclosed|any|apply|source|location|posted|results|noresults|annual|yearfrom|yearto|initial|current|calculate|amount|back|more|region|all|alljobs|jobnote|wagesnote|powernote|fxnote|settingsnote|apiversion|profession|age|days|original|nomatch|retry|sourcecheck|nethint|employers|filters|native|data|status|value|official|monthly|selected|countryhint".split("|")
private val words = mapOf(
"en" to "Home|Compare|Jobs|Settings|Salaries|Tools|Inflation|Purchasing power|Currency exchange|About EarnWage|Country|Destination|Occupation|Search|Language|Display currency|Appearance|System|Light|Dark|Start EarnWage|Your salary. Your world.|Choose your preferences|Open|Unavailable|Loading…|Remote only|Published salary|Any|View vacancy / Apply|Source|Location|Date|results|No matching vacancies|Annual gross salary (optional)|From year|To year|Previous income|Current income|Calculate|Amount in EUR|Back|More tools|State / province (optional)|All|All jobs|Eligibility and vacancy availability must be confirmed at source.|National observations are not a job offer or a city salary.|Use verified national observations or explicitly entered inflation; no estimates are substituted.|ECB reference rates, not bank retail prices.|Your preferences are saved on this device.|API version|Profession|Age limit|days|Original|No validated observation available|Try again|Check original source|Partial tax data are not net income.|Employers|Filters|Original currency retained|Data and methodology|Status|Value|Verified|Monthly|Selected|The chosen currency defaults the exchange tool; original wages and job salaries are never silently converted.".split("|"),
"pt" to "Início|Comparar|Empregos|Definições|Salários|Ferramentas|Inflação|Poder de compra|Câmbio|Sobre a EarnWage|País|Destino|Profissão|Pesquisar|Idioma|Moeda de apresentação|Aparência|Sistema|Claro|Escuro|Entrar na EarnWage|O teu salário. O teu mundo.|Escolhe as tuas preferências|Abrir|Indisponível|A carregar…|Só remoto|Salário publicado|Qualquer|Ver oferta / Candidatar-me|Fonte|Localização|Data|resultados|Sem ofertas correspondentes|Salário bruto anual (opcional)|Ano inicial|Ano final|Rendimento anterior|Rendimento atual|Calcular|Montante em EUR|Voltar|Mais ferramentas|Estado / província (opcional)|Todas|Todas as ofertas|Confirma sempre a elegibilidade e disponibilidade na oferta original.|Os dados nacionais não são uma oferta de emprego nem salários de uma cidade.|Usamos observações nacionais verificadas ou inflação introduzida explicitamente; não substituímos valores em falta.|Taxas de referência do BCE, não taxas bancárias de retalho.|As preferências ficam guardadas neste dispositivo.|Versão da API|Profissão|Idade máxima|dias|Original|Sem observação validada disponível|Tentar novamente|Consultar fonte original|Dados fiscais parciais não são salário líquido.|Empresas|Filtros|Moeda original preservada|Dados e metodologia|Estado|Valor|Verificado|Mensal|Selecionado|A moeda escolhida predefine a ferramenta de câmbio; salários estatísticos e anúncios nunca são convertidos sem indicação.".split("|"),
"es" to "Inicio|Comparar|Empleos|Ajustes|Salarios|Herramientas|Inflación|Poder adquisitivo|Divisas|Acerca de EarnWage|País|Destino|Profesión|Buscar|Idioma|Moneda de visualización|Apariencia|Sistema|Claro|Oscuro|Entrar en EarnWage|Tu salario. Tu mundo.|Elige tus preferencias|Abrir|No disponible|Cargando…|Solo remoto|Salario publicado|Cualquiera|Ver oferta / Solicitar|Fuente|Ubicación|Fecha|resultados|Sin ofertas coincidentes|Salario bruto anual (opcional)|Año inicial|Año final|Ingreso anterior|Ingreso actual|Calcular|Importe en EUR|Volver|Más herramientas|Estado / provincia (opcional)|Todas|Todos los empleos|Comprueba la elegibilidad y disponibilidad en la fuente.|Los datos nacionales no son ofertas ni salarios urbanos.|Utiliza observaciones verificadas o la inflación introducida por el usuario.|Tipos de referencia del BCE, no bancarios.|Tus preferencias se guardan en este dispositivo.|Versión API|Profesión|Antigüedad máxima|días|Original|Sin observaciones verificadas|Reintentar|Ver fuente original|Los impuestos parciales no son salario neto.|Empresas|Filtros|Se conserva la moneda original|Datos y metodología|Estado|Valor|Verificado|Mensual|Seleccionado|La moneda elegida preselecciona el conversor; los salarios originales no se convierten silenciosamente.".split("|"),
"fr" to "Accueil|Comparer|Emplois|Paramètres|Salaires|Outils|Inflation|Pouvoir d’achat|Devises|À propos d’EarnWage|Pays|Destination|Métier|Rechercher|Langue|Devise d’affichage|Apparence|Système|Clair|Sombre|Entrer dans EarnWage|Votre salaire. Votre monde.|Choisissez vos préférences|Ouvrir|Indisponible|Chargement…|Télétravail uniquement|Salaire publié|Tous|Voir l’offre / Postuler|Source|Lieu|Date|résultats|Aucune offre correspondante|Salaire brut annuel (facultatif)|Année de début|Année de fin|Revenu antérieur|Revenu actuel|Calculer|Montant en EUR|Retour|Autres outils|État / province (facultatif)|Toutes|Toutes les offres|Vérifiez l’éligibilité et la disponibilité à la source.|Les données nationales ne sont ni des offres ni des salaires urbains.|Observations vérifiées ou inflation saisie explicitement.|Taux de référence BCE, pas taux bancaires.|Préférences enregistrées sur cet appareil.|Version API|Métier|Âge maximum|jours|Original|Aucune observation validée|Réessayer|Voir la source|Les données fiscales partielles ne sont pas le salaire net.|Employeurs|Filtres|Devise d’origine préservée|Données et méthodologie|Statut|Valeur|Vérifié|Mensuel|Sélectionné|La devise choisie présélectionne le convertisseur; les salaires d’origine ne sont pas convertis silencieusement.".split("|"),
"de" to "Start|Vergleichen|Jobs|Einstellungen|Gehälter|Werkzeuge|Inflation|Kaufkraft|Wechselkurse|Über EarnWage|Land|Zielland|Beruf|Suchen|Sprache|Anzeigewährung|Darstellung|System|Hell|Dunkel|EarnWage starten|Dein Gehalt. Deine Welt.|Einstellungen wählen|Öffnen|Nicht verfügbar|Lädt…|Nur Remote|Gehalt veröffentlicht|Beliebig|Stelle ansehen / Bewerben|Quelle|Ort|Datum|Ergebnisse|Keine passenden Stellen|Bruttojahresgehalt (optional)|Startjahr|Endjahr|Früheres Einkommen|Aktuelles Einkommen|Berechnen|Betrag in EUR|Zurück|Weitere Werkzeuge|Bundesland / Provinz (optional)|Alle|Alle Stellen|Eignung und Verfügbarkeit bei der Quelle prüfen.|Landeswerte sind keine Stellenangebote oder Stadtgehälter.|Geprüfte Werte oder ausdrücklich eingegebene Inflation.|EZB-Referenzkurse, keine Bankkurse.|Einstellungen werden auf diesem Gerät gespeichert.|API-Version|Beruf|Maximales Alter|Tage|Original|Keine geprüften Daten verfügbar|Erneut versuchen|Originalquelle prüfen|Teilweise Steuerdaten sind kein Nettogehalt.|Arbeitgeber|Filter|Originalwährung bleibt erhalten|Daten und Methodik|Status|Wert|Geprüft|Monatlich|Ausgewählt|Die gewählte Währung gilt für das Wechselkurswerkzeug; ursprüngliche Gehälter werden nicht stillschweigend umgerechnet.".split("|"),
"it" to "Home|Confronta|Lavori|Impostazioni|Stipendi|Strumenti|Inflazione|Potere d’acquisto|Cambio valuta|Informazioni su EarnWage|Paese|Destinazione|Professione|Cerca|Lingua|Valuta di visualizzazione|Aspetto|Sistema|Chiaro|Scuro|Apri EarnWage|Il tuo stipendio. Il tuo mondo.|Scegli le preferenze|Apri|Non disponibile|Caricamento…|Solo remoto|Stipendio pubblicato|Qualsiasi|Vedi offerta / Candidati|Fonte|Luogo|Data|risultati|Nessuna offerta corrispondente|Stipendio lordo annuo (opzionale)|Anno iniziale|Anno finale|Reddito precedente|Reddito attuale|Calcola|Importo in EUR|Indietro|Altri strumenti|Stato / provincia (opzionale)|Tutti|Tutti i lavori|Verifica idoneità e disponibilità alla fonte.|I dati nazionali non sono offerte o stipendi cittadini.|Osservazioni verificate o inflazione inserita esplicitamente.|Tassi BCE, non cambi bancari.|Preferenze salvate sul dispositivo.|Versione API|Professione|Età massima|giorni|Originale|Nessuna osservazione verificata|Riprova|Verifica fonte originale|I dati fiscali parziali non sono stipendio netto.|Aziende|Filtri|Valuta originale conservata|Dati e metodologia|Stato|Valore|Verificato|Mensile|Selezionato|La valuta scelta imposta il convertitore; gli stipendi originali non sono convertiti automaticamente.".split("|"),
"nl" to "Start|Vergelijken|Banen|Instellingen|Salarissen|Hulpmiddelen|Inflatie|Koopkracht|Wisselkoersen|Over EarnWage|Land|Bestemming|Beroep|Zoeken|Taal|Weergavevaluta|Weergave|Systeem|Licht|Donker|EarnWage openen|Jouw salaris. Jouw wereld.|Kies je voorkeuren|Openen|Niet beschikbaar|Laden…|Alleen op afstand|Salaris vermeld|Alle|Vacature bekijken / Solliciteren|Bron|Locatie|Datum|resultaten|Geen passende vacatures|Bruto jaarsalaris (optioneel)|Beginjaar|Eindjaar|Vorig inkomen|Huidig inkomen|Berekenen|Bedrag in EUR|Terug|Meer hulpmiddelen|Staat / provincie (optioneel)|Alle|Alle banen|Controleer geschiktheid en beschikbaarheid bij de bron.|Landelijke cijfers zijn geen vacatures of stadsalarissen.|Geverifieerde gegevens of zelf ingevoerde inflatie.|ECB-referentiekoersen, geen bankkoersen.|Voorkeuren opgeslagen op dit apparaat.|API-versie|Beroep|Maximale leeftijd|dagen|Origineel|Geen gevalideerde gegevens|Opnieuw proberen|Oorspronkelijke bron|Gedeeltelijke belastinggegevens zijn geen nettoloon.|Werkgevers|Filters|Oorspronkelijke valuta behouden|Gegevens en methodologie|Status|Waarde|Geverifieerd|Maandelijks|Geselecteerd|Gekozen valuta stelt het wisselkoershulpmiddel in; oorspronkelijke salarissen worden niet stilzwijgend omgerekend.".split("|")
)
internal fun tr(language: String, key: String): String {
    val n = keys.indexOf(key)
    if (n < 0) return key
    return words[language]?.getOrNull(n) ?: words["en"]?.getOrNull(n) ?: key
}
internal fun countryFlag(code: String): String {
    if (code.length != 2 || code.any { it !in 'A'..'Z' }) return "🌐"
    return String(Character.toChars(0x1F1E6 + code[0].code - 65)) +
        String(Character.toChars(0x1F1E6 + code[1].code - 65))
}
